---
author: "Michael Karp"
title: "Reproducible Research: Peer Assessment 1"
date: 1/18/2014
output: 
html_document:
keep_md: true
---


## Loading and preprocessing the data
```{r, echo = TRUE, results='asis'}
activity_data = read.csv("activity.csv")
# inspect acitivity data
str(activity_data)

# convert date variable into date object
activity_data$date = as.character(activity_data$date)
activity_data$date = as.Date(activity_data$date)
str(activity_data)
summary(activity_data)
```

## What is mean total number of steps taken per day?
```{r, echo = TRUE, results='asis'}
#histogram of steps
step_hist <- hist(activity_data$steps)

## Calculate and report the mean and median total number of steps taken per day
mu_steps <- mean(activity_data$steps, na.rm = TRUE)
mu_steps
# 37.3826

median_steps <- median(activity_data$steps, na.rm = TRUE)
median_steps
# 0
```

## What is the average daily activity pattern?
```{r, echo = TRUE, results='asis'}
# table of means of steps taken per interval
mean_step_interval <- tapply(activity_data$steps, activity_data$interval, mean, na.rm = TRUE)
# plot of activity
plot_ts <- plot(type = 'l', as.numeric(names(mean_step_interval)), mean_step_interval, xlab = "Interval", ylab = "Mean Steps Taken")

# Which 5-minute interval, on average across all the days in the dataset, contains the maximum number of steps?
max_avg_steps_taken <- which.max(mean_step_interval)
max_avg_steps_taken
mean_step_interval[104]
```

## Imputing missing values
```{r, echo = TRUE, results='asis'}
# Calculate and report the total number of missing values in the dataset (i.e. the total number of rows with NAs)
num_na <- sum(is.na(activity_data))
num_na

# only steps taken has missing values so we replace these with the mean
summary(activity_data)
str(activity_data)
imputed_activity_data <- activity_data
imputed_activity_data$steps[is.na(imputed_activity_data$steps)] <- mean(imputed_activity_data$steps, na.rm = TRUE)
str(imputed_activity_data)
summary(imputed_activity_data)
```

## Are there differences in activity patterns between weekdays and weekends?
```{r, echo = TRUE, results='asis', fig.height=4}
imputed_activity_data$weekday_bool <- weekdays(imputed_activity_data$date) == "Saturday" | weekdays(imputed_activity_data$date) == "Sunday"
levels(imputed_activity_data$weekday_bool) <- c("Weekday", "Weekend")
imputed_activity_data$weekday_bool[imputed_activity_data$weekday_bool == TRUE] <- "Weekend" 
imputed_activity_data$weekday_bool[imputed_activity_data$weekday_bool == FALSE] <- "Weekday" 

library(ggplot2)
imputed_activity_data$mean_step_interval <- tapply(imputed_activity_data$steps, imputed_activity_data$interval, mean)
# plot of activity
activity_plot <- ggplot(data = imputed_activity_data, aes(x = interval, y = mean_step_interval)) + geom_line() + xlab("Interval") + ylab("Mean Steps Taken")
activity_plot + facet_grid(weekday_bool~.)
```

